using ModletBuilder.Core.Generation;
using ModletBuilder.Core.Logging;
using ModletBuilder.Core.Models;

namespace ModletBuilder.Tests;

internal sealed class TestMarkdownToBbCodeConverter : IMarkdownToBbCodeConverter
{
    private readonly IReadOnlyList<Diagnostic> _diagnostics;
    private readonly bool _writeOutput;
    private readonly string? _fixedOutput;

    internal TestMarkdownToBbCodeConverter(
        IReadOnlyList<Diagnostic>? diagnostics = null,
        bool writeOutput = true,
        string? fixedOutput = null)
    {
        _diagnostics = diagnostics ?? [];
        _writeOutput = writeOutput;
        _fixedOutput = fixedOutput;
    }

    internal bool WasCalled { get; private set; }

    internal string? MarkdownPath { get; private set; }

    internal string? OutputPath { get; private set; }

    public IReadOnlyList<Diagnostic> Convert(
        string markdownPath,
        string outputPath,
        BuildLogger logger)
    {
        WasCalled = true;
        MarkdownPath = markdownPath;
        OutputPath = outputPath;

        if (_diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error))
            return _diagnostics;

        if (_writeOutput)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
            File.WriteAllText(outputPath, _fixedOutput ?? BuildDefaultOutput(markdownPath));
        }

        return _diagnostics;
    }

    private static string BuildDefaultOutput(string markdownPath)
    {
        var heading = File.ReadLines(markdownPath)
            .Select(line => line.Trim())
            .FirstOrDefault(line => line.StartsWith("# ", StringComparison.Ordinal));

        var title = heading is null
            ? Path.GetFileNameWithoutExtension(markdownPath)
            : heading[2..];

        return $"[size=6][b]{title}[/b][/size]\n\nGenerated by test Markdown converter.\n";
    }
}
